name: Deploy to Salesforce & Trigger Kamikaze

# Trigger on push to main branch
on:
  push:
    branches: [ "main", "test2", "test4", "test6", "test7" , "test8" ,"KAN-9","khush12345-cmd-patch1" ]
    paths-ignore:
      - '.github/**'

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Install Node.js (Required for Salesforce CLI)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Install Salesforce CLI
      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      # 4. Authenticate to Salesforce (Using the Secret)
      - name: Authenticate to Salesforce
        run: |
          echo "${{ secrets.SFDX_AUTH_URL }}" > auth_url.txt
          sf org login sfdx-url --sfdx-url-file auth_url.txt --set-default --alias staging-org
          rm auth_url.txt

      # 5. Deploy Code to Salesforce
      # This pushes your Apex/LWC changes to the Org
      - name: Deploy Source
        run: sf project deploy start --target-org staging-org --source-dir force-app --wait 10

    
